run:
  deadline: 10m

linters-settings:
  gocyclo:
    min-complexity: 30
  lll:
    line-length: 180
  gci:
    sections:
      - standard
      - default
      - blank
      - dot
    skip-generated: false
    custom-order: true
  goconst:
    ignore-strings: "true|false"
  errcheck:
    check-type-assertions: true
  exhaustive:
    check:
      - switch
    default-signifies-exhaustive: true
  funlen:
    lines: 100
    statements: 100
    ignore-comments: true
  nolintlint:
    allow-no-explanation: [ funlen, lll ]
    require-specific: true
  ireturn:
    allow:
      # defaults https://golangci-lint.run/usage/linters/#ireturn
      - anon
      - error
      - empty
      - stdlib
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages: ["github.com/onsi/ginkgo/v2","github.com/onsi/gomega","github.com/onsi/gomega/gstruct"]
  perfsprint:
    sprintf1: false
    strconcat: false
  # Enable gocritic for detecting bugs, performance, and style issues: https://golangci-lint.run/usage/linters/#gocritic
  gocritic:
    # https://go-critic.com/overview.html#checkers
    enabled-checks:
      - deferInLoop
      - unnecessaryDefer

linters:
  enable-all: true
  disable:
    - depguard # [replaced by gomodguard] checks if package imports are in a list of acceptable packages
    - exhaustruct # Prevents empty struct. We use a lot of these so I think it is safe to disable.c
    - forbidigo
    - gochecknoglobals # Prevents use of global vars.
    - gofumpt
    - gomoddirectives # Doesnot allow replace in go mod file
    - mnd
    - nestif
    - nilnil
    - paralleltest # [too many false positives] detects missing usage of t.Parallel() method in your Go test
    - tagliatelle
    - varnamelen # doesnot allow shorter names like c,k etc. But golang prefers short named vars.
    - wsl # [too strict and mostly code is not more readable] whitespace linter forces you to use empty lines
    - wrapcheck # check if this is required. Prevents direct return of err.
    - exportloopref # Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.

    # Need to check
    - nlreturn # [too strict and mostly code is not more readable] checks for a new line before return and branch statements to increase code clarity
    - err113 # [too strict] checks the errors handling expressions


issues:
  exclude-dirs:
    - apis