# This configmap contains the distribution images for the llama-stack operator
# The configmap should only be updated at build time.
apiVersion: v1
kind: ConfigMap
metadata:
  name: distribution-images
  namespace: system
# The distribution images are immutable and should not be updated
immutable: true
data:
  starter: docker.io/llamastack/distribution-starter:0.2.9
  ollama: docker.io/llamastack/distribution-ollama:0.2.9
  bedrock: docker.io/llamastack/distribution-bedrock:0.2.9
  remote-vllm: docker.io/llamastack/distribution-remote-vllm:0.2.9
  tgi: docker.io/llamastack/distribution-tgi:0.2.9
  together: docker.io/llamastack/distribution-together:0.2.9
  vllm-gpu: docker.io/llamastack/distribution-vllm-gpu:0.2.9
