apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

## Append samples you want in your CSV to this file as resources ##
resources:
- v1alpha1/llamastackdistribution.yaml
- v1alpha1/example-with-configmap.yaml
- v1alpha1/example-with-ca-bundle.yaml
- v1alpha1/example-with-network-config.yaml
