name: Build CPU-only vLLM Image

on:
  # Because it is challenging to trigger this workflow every time the vLLM
  # maintainers publish a new release/tag, we can at least setup a cronjob
  # to update the image once a week.
  schedule:
    - cron: '0 0 * * FRI' # Runs at 12AM UTC on Fridays
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  VLLM_CPU_IMAGE: "quay.io/llamastack/vllm-cpu"

jobs:
  build-latest-vllm-cpu-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      # We need to clone vLLM first to identify latest tags unless we want to use the GH API.
      - name: Clone vLLM
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: vllm-project/vllm
          path: vllm
          fetch-depth: 0 # Fetch all history to find the latest tag

      - name: Get latest vLLM release tag
        id: get_latest_vllm_release
        run: |
          cd vllm
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "::set-output name=tag::${LATEST_TAG}"

      - name: Checkout latest vLLM release
        run: cd vllm && git checkout tags/${{ steps.get_latest_vllm_release.outputs.tag }}
        shell: bash

      - name: Login to Quay.io
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: quay.io
          username: ${{ secrets.APP_QUAY_USERNAME }}
          password: ${{ secrets.APP_QUAY_TOKEN }}

      - name: Build and push latest vLLM CPU image
        run: |
           cd vllm
           export vllm_version="${{ steps.get_latest_vllm_release.outputs.tag }}"
           podman build --security-opt label=disable -f docker/Dockerfile.cpu --build-arg VLLM_CPU_AVX512BF16=false  --build-arg VLLM_CPU_AVX512VNNI=false --tag ${VLLM_CPU_IMAGE}:${vllm_version} --target vllm-openai .
           make image-push -e IMG=${VLLM_CPU_IMAGE}:${vllm_version}
           cd ..
           if [[ "$vllm_version" =~ [Aa] ]] || [[ "$vllm_version" =~ [Bb] ]] || [[ "$vllm_version" =~ [Rr]c ]]; then
             echo "Image succesfully pushed to quay.io, but refusing to overwrite the `latest` tag with for vLLM ${vllm_version} because it is either an alpha, beta, or release candidate."
           else
             podman tag ${VLLM_CPU_IMAGE}:${vllm_version} ${VLLM_CPU_IMAGE}:latest
             make image-push -e IMG=${VLLM_CPU_IMAGE}:latest
           fi
        shell: bash
