name: Unit and Functional Test Code Coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run tests
        run: |
          make test

      - name: Run test coverage check
        uses: GoTestTools/limgo-action@v1.0.0
        with:
          version: "v1.0.0"
          args: "-coverfile=cover.out -outfile=covcheck.tmp -config=.limgo.json -v=3"

      - name: Upload test coverage results
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: test-coverage-results
          path: covcheck.tmp
          if-no-files-found: error
